#!/bin/bash

shopt -s nocasematch
readonly program="$(basename "${0}")"

usage() {
  cat <<EOF
usage: $program [options] <asn>

options:
  -4, --ipv4               IPv4 routes only.
  -6, --ipv6               IPv6 routes only.
  -h, --help               Show this help message.
EOF
}

syntax_error() {
  echo "${program}: ${1}"
  echo "${program}: try '${program} --help' for more information."
  exit 1
}

while [[ "$1" ]]; do
  case "$1" in
    -h | --help)
      usage
      exit 0
      ;;
    -4 | --ipv4)
      ipv4=true
      ;;
    -6 | --ipv6)
      ipv6=true
      ;;
    -*)
      syntax_error "invalid option -- $1"
      ;;
    *)
      break
      ;;
  esac
  shift
done

if [[ -z ${1} ]]; then
usage
  exit 1
fi

asn="${1}"

if [[ ! $asn =~ ^(:?as)?[0-9]+$ ]]; then
  echo 'No valid ASN specified.'
  usage
  exit 1
fi

output=$(whois -h whois.radb.net -- -i origin "$asn")

if [ "$ipv4" = true ] ; then
  echo "$output" | gawk '/route:/ { print $2}'
elif [ "$ipv6" = true ] ; then
  echo "$output" | gawk '/route6:/ { print $2}'
else
  echo "$output" | gawk '/route6?:/ { print $2}'
fi
