#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

readonly program="$(basename "${0}")"

if [ ${#BASH_ARGV[@]} -eq 0 ]; then
  echo "usage: $program <url>"
  exit 1
fi

readonly url=${BASH_ARGV[0]}

args=("$@")
unset "args[${#args[@]}-1]"

# source: https://git.io/v9GCa
format="    time_namelookup:  %{time_namelookup}
       time_connect:  %{time_connect}
    time_appconnect:  %{time_appconnect}
   time_pretransfer:  %{time_pretransfer}
      time_redirect:  %{time_redirect}
 time_starttransfer:  %{time_starttransfer}
                    ---------
         time_total:  %{time_total}"

args+=(-w "$format")
args+=(-o /dev/null)
args+=(-s)

curl "${args[@]}" "$url"
