#!/bin/bash

readonly program="$(basename "${0}")"

if [[ -z "$1" ]]; then
  echo "usage: $program <URL>"
  exit 1
fi

# source: https://blog.josephscott.org/2011/10/14/timing-details-with-curl/
format="    time_namelookup:  %{time_namelookup}
       time_connect:  %{time_connect}
    time_appconnect:  %{time_appconnect}
   time_pretransfer:  %{time_pretransfer}
      time_redirect:  %{time_redirect}
 time_starttransfer:  %{time_starttransfer}
                    ---------
         time_total:  %{time_total}"

curl -w "$format" -o /dev/null -s "$1"
