#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o errtrace
set -o pipefail

# shellcheck disable=SC2034
DEFAULT_IFS="${IFS}"
SAFER_IFS=$'\n\t'
IFS="${SAFER_IFS}"

_ME=$(basename "${0}")

_print_help() {
  cat <<HEREDOC
usage:
  ${_ME} <gem>
  ${_ME} -h | --help
options:
  -h --help  Show this screen.
HEREDOC
}

_ungem() {
  gem_path="$1"
  temp_dir="$(mktemp -d)"

  tar xf "$gem_path" -C "$temp_dir"
  tar xzf "$temp_dir/data.tar.gz" -C "$PWD"
}

_main() {
  if [[ "${1:-}" =~ ^-h|--help$  ]]
  then
    _print_help
  else
    _ungem "$@"
  fi
}

_main "$@"
