#!/bin/bash

if (( $# == 0 )) ; then
  input="$(cat /dev/stdin)"
else
  input="$1"
fi

length="${#input}"

for (( i = 0; i < length; i++ )); do
  c="${input:i:1}"
  case $c in
    [a-zA-Z0-9.~_-]) printf "%s" "$c" ;;
    *) printf "%%%02X" "'$c"
  esac
done
