#!/bin/bash

urlencode() {
  local LANG=C i=0 c e s="$1"

  while [ $i -lt ${#1} ]; do
    [ "$i" -eq 0 ] || s="${s#?}"
    c=${s%"${s#?}"}
    [ -z "${c#[[:alnum:].~_-]}" ] || c=$(printf "%%%02X" "'$c")
    e="${e}${c}"
    i=$((i + 1))
  done
  echo "$e"
}

if (( $# == 0 )) ; then
  input="$(cat /dev/stdin)"
else
  input="$1"
fi

urlencode "$input"
